### ISSUE TITLE
Market broke in my smartphone since the update

### ISSUE THREAD

**Issue by robertopc** [mozilla/fireplace#1317]
Hi,
I have LG Fireweb model LGD300F with OS version 1.1.0.1(mobile operator doesn't update the firmware).
Observable issues:
* search not work
* icons have a irregular size
* some apps in list break the viewport
* buttons not aligned

Follow some prints with related issues.

![2015-06-16-11-18-27](https://cloud.githubusercontent.com/assets/1685216/8185296/b66bf42a-1419-11e5-9fb1-e12981a8efaa.png)
![2015-06-16-11-17-49](https://cloud.githubusercontent.com/assets/1685216/8185297/b747cc2a-1419-11e5-8b4d-d9eb9c5188e9.png)
![2015-06-16-11-17-57](https://cloud.githubusercontent.com/assets/1685216/8185298/b74ed45c-1419-11e5-8025-4dad38c4bb24.png)
![2015-06-16-11-18-11](https://cloud.githubusercontent.com/assets/1685216/8185299/b78b51de-1419-11e5-875f-a4c561fbaaff.png)
![2015-06-16-11-28-14](https://cloud.githubusercontent.com/assets/1685216/8185457/ef087884-141a-11e5-8208-438f129a2540.png)
![2015-06-16-11-26-41](https://cloud.githubusercontent.com/assets/1685216/8185453/eee5ee40-141a-11e5-90e7-6f0789da1e4a.png)
![2015-06-16-11-26-51](https://cloud.githubusercontent.com/assets/1685216/8185454/eeee3488-141a-11e5-9f5e-6858b53f9b1e.png)
![2015-06-16-11-27-04](https://cloud.githubusercontent.com/assets/1685216/8185455/eef40a48-141a-11e5-8d9b-e68828e38bb7.png)
![2015-06-16-11-27-13](https://cloud.githubusercontent.com/assets/1685216/8185456/eef7a37e-141a-11e5-82d8-f39d3c33984f.png)

**Comment by jesobreira** [comment]
Hi!

Search form not working was fixed on #1509 .

Marketplace has received many improvements recently, but I think the most urgent is to fix the "More" and "Categories" panels floating in front of the page content, making it impossible to use Marketplace on 1.1. I've fixed it in #1570 but it's still under tests.

As soon as these panels' issues are fixed (and Marketplace is "useable") I will take a look on the other bugs too.
