### ISSUE TITLE
if the **collection_colors.styl** is removed in the *css/lib*

### ISSUE THREAD

**Issue by betterliuyu** [mozilla/fireplace#1484]
Dear developer, as the title describes, the **collection_colors.styl** is not seen in the *css/lib*, but the **index.styl** in the same directory import the collection_colors.styl file, such as *@import 'collection_colors';*. So, I don't know if it is a bug.

**Comment by ngokevin** [comment]
Thanks for the report. It's actually installed through a Bower dependency at [marketplace-constants](http://github.com/mozilla/marketplace-constants).
