### ISSUE TITLE
Search is broken on dev and staging

### ISSUE THREAD

**Issue by davehunt** [mozilla/fireplace#1597]
**Steps to reproduce:**

  1. Open https://marketplace-dev.allizom.org/
  1. Click the search icon
  1. Enter a search term
  1. Press return

**Expected:**
Search results displayed.

**Actual:**
Nothing. The following is logged to the console:

> ReferenceError: $currentForm is not defined

This is affecting the automated functional tests, and appears to have started failing between [Jan 8, 2016 6:44:23 PM](https://webqa-ci.mozilla.com/view/Marketplace/job/marketplace.dev.saucelabs/738/) and [Jan 9, 2016 11:15:00 AM](https://webqa-ci.mozilla.com/view/Marketplace/job/marketplace.dev.saucelabs/739/).

**Comment by diox** [comment]
Thanks, this has already been logged : https://bugzilla.mozilla.org/show_bug.cgi?id=1164857#c38
