### ISSUE TITLE
CSS issue with the validation tooltip on https://marketplace.firefox.com/fxa-migration 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fireplace#910]
The arrow offset seems to be wrong in Chrome and FF on OS X.

![image](https://cloud.githubusercontent.com/assets/128755/5751812/8ad899d0-9c37-11e4-8da0-76ee4abce4bf.png)

**Comment by spasovski** [comment]
Seems consistent. Where do you expect it to be?

**Comment by vladikoff** [comment]
The correct style is this:

![image](https://cloud.githubusercontent.com/assets/128755/5752104/d361cf0a-9c3c-11e4-8e6a-c4851ca7e2d2.png)

**Comment by spasovski** [comment]
Been a long day. Yea the arrow looks like a diamond otherwise.

**Comment by mstriemer** [comment]
We're dropping the migration flow this week so this will go away.
