### ISSUE TITLE
Region showing Indonedsia instead of India.

### ISSUE THREAD

**Issue by akshatkedia** [mozilla/fireplace#913]
![marketplace](https://cloud.githubusercontent.com/assets/5302479/5774971/1111ad12-9d9a-11e4-988d-b94830291281.PNG)
As it can be seen in the image above, it's showing the flag of India but it's written Indonesia instead.

**Comment by muffinresearch** [comment]
Re-filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1122588

**Comment by muffinresearch** [comment]
Thanks for the report.
